// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// processFloWave2
Rcpp::NumericVector processFloWave2(Rcpp::CharacterVector input, Rcpp::CharacterVector output);
RcppExport SEXP _rLVIS_processFloWave2(SEXP inputSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(processFloWave2(input, output));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rLVIS_processFloWave2", (DL_FUNC) &_rLVIS_processFloWave2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rLVIS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
